name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/checkout@v2

      - name: Set up Go
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Go mods
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: go mod download

      - name: Setup windows libs
        if: ${{ startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/v') }}
        run: brew install mingw-w64

      - name: Build linux cli binary file
        if: ${{ startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v') }}
        run: env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o release/linyx-keyvault-cli ./cli

      - name: Build windows cli binary file
        if: ${{ startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/v') }}
        run: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -buildmode=c-shared -o release/keyvault-cli.exe ./cli

      - name: Build macos cli binary file
        if: ${{ startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/v') }}
        run: go build -o release/macos-keyvault-cli ./cli

      - name: Release assets
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "release/*"
          token: ${{ secrets.GITHUB_TOKEN }}
